import Notification from "@/components/Notification";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ClientOnly from "@/components/ClientOnly";
import AuthProvider from "@/components/AuthProvider";
import ReactQueryProvider from "@/components/ReactQueryProvider";
import { ToastProvider } from "@/components/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <AuthProvider>
            <ReactQueryProvider>
              <ToastProvider>
                <ClientOnly>
                  <Notification />
                  <Navbar />
                  {children}
                  <Footer />
                </ClientOnly>
              </ToastProvider>
            </ReactQueryProvider>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
